swagger: '2.0'
info:
  title: ORDS generated API for web
  version: 1.0.0
host: dev.jag.gov.bc.ca
basePath: "/ords/deva/rsdfrmords/web"
schemes:
- https
produces:
- application/json
paths:
  "/health":
    get:
      tags:
      - Health
      operationId: health
      description: Dummy endpoint to check that API calls are working
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/healthOrdsResponse'
  "/digitalForm":
    post:
      tags:
      - Application
      description: Create digital form
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": "#/definitions/digitalFormCreateResponse"
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/digitalFormErrorResponse'
      consumes:
      - application/json
      parameters:
      - name: payload
        in: body
        required: true
        schema:
          "$ref": "#/definitions/digitalFormPostRequest"
  "/digitalForm/{guid}":
    get:
      tags:
      - Application
      description: Get digital form
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": "#/definitions/digitalFormGetResponse"
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/digitalFormErrorResponse'
      parameters:
      - name: guid
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
    patch:
      tags:
      - Application
      description: Patch digital form
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": "#/definitions/digitalFormPatchResponse"
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/digitalFormErrorResponse'
      consumes:
      - application/json
      parameters:
      - name: guid
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: payload
        in: body
        required: true
        schema:
          "$ref": "#/definitions/digitalFormPatchRequest"
definitions:
  healthOrdsResponse:
    type: object
    required:
    - appid
    - method
    - status
    - host
    - instance
    properties:
      appid:
        type: string
      method:
        type: string
      status:
        type: string
      host:
        type: string
      instance:
        type: string
  digitalFormPostRequest:
    properties:
      user_id:
        type: string
      prohibition_notice_no:
        type: string
      notice_subject_cd:
        type: string
      notice_type_cd:
        type: string
      review_application_type_cd:
        type: string
      presentation_format_cd:
        type: string
      review_role_type_cd:
        type: string
      hearing_dt:
        type: string
      hearing_start_tm:
        type: string
      hearing_end_tm:
        type: string
      application_received_dt:
        type: string
      receipt_number_txt:
        type: string
      first_given_nm:
        type: string
      second_given_nm:
        type: string
      surname_nm:
        type: string
      phone_no:
        type: string
      fax_no:
        type: string
      electronic_address_txt:
        type: string
      manual_entry_yn:
        type: string
      form_xml:
        type: string
  digitalFormPatchRequest:
    properties:
      user_id:
        type: string
      prohibition_notice_no:
        type: string
      notice_subject_cd:
        type: string
      notice_type_cd:
        type: string
      review_application_type_cd:
        type: string
      presentation_format_cd:
        type: string
      review_role_type_cd:
        type: string
      hearing_dt:
        type: string
      hearing_start_tm:
        type: string
      hearing_end_tm:
        type: string
      application_received_dt:
        type: string
      receipt_number_txt:
        type: string
      first_given_nm:
        type: string
      second_given_nm:
        type: string
      surname_nm:
        type: string
      phone_no:
        type: string
      fax_no:
        type: string
      electronic_address_txt:
        type: string
      manual_entry_yn:
        type: string
      form_xml:
        type: string
  digitalFormGetResponse:
    properties:
      status_code:
        type: string
      status_message:
        type: string
      user_id:
        type: string
      prohibition_notice_no:
        type: string
      notice_subject_cd:
        type: string
      notice_type_cd:
        type: string
      review_application_type_cd:
        type: string
      presentation_format_cd:
        type: string
      review_role_type_cd:
        type: string
      first_given_nm:
        type: string
      second_given_nm:
        type: string
      surname_nm:
        type: string
      phone_no:
        type: string
      fax_no:
        type: string
      electronic_address_txt:
        type: string
      manual_entry_yn:
        type: string
      form_xml:
        type: string
  digitalFormCreateResponse:
    properties:
      status_code:
        type: string
      status_message:
        type: string
      form_object_guid:
        type: string
      ent_dtm:
        type: string
  digitalFormPatchResponse:
    properties:
      status_code:
        type: string
      status_message:
        type: string
      form_object_guid:
        type: string
      upd_dtm:
        type: string
  digitalFormErrorResponse:
    properties:
      status_code:
        type: string
      status_message:
        type: string
